/**
 * The apparel the house sells, which until now the site did not know about
 * at all.
 *
 * ---- Why this is a file of its own ----
 *
 * `lib/catalogue.ts` is generated by `scripts/sync-catalogue.mjs` from the
 * storefront's eyewear collections, and it says at the top not to edit it by
 * hand — correctly, since hand-editing a generated file is how a second
 * catalogue gets born. Apparel is not in what that script reads, so it lives
 * here instead of being smuggled into a file that will be overwritten.
 *
 * ---- One garment, five colourways ----
 *
 * The same shape the eyewear takes: a collection whose members are
 * colourways rather than separate products, sold at one price with a
 * compare-at above it. Sizes are the one thing eyewear does not have — a
 * frame is cut to one set of measurements and a sweater is not — so they
 * are carried here and nowhere else.
 *
 * Read from the store's own records via `scripts/group_colorways.py`; the
 * photography came in through `scripts/import-colourway-photography.mjs`
 * alongside the houses.
 */

export type ApparelColourway = {
  name: string;
  /** Shopify product handle. Irregular, like the eyewear's — three of these
   *  are `alpaca-sweater-*` and two are `baby-alpaca-sweater-*`. */
  handle: string;
  /** For `/cart/<id>:<qty>` checkout permalinks, as the eyewear does. */
  variantId: number;
  cents: number;
  /** What it was, where the store shows a price it has come down from. */
  compareAtCents?: number;
  available: boolean;
  image?: string;
  swatch: string;
};

export type ApparelCollection = {
  name: string;
  slug: string;
  /** What it is made of, in the voice the houses use for their material. */
  material: string;
  note: string;
  sizes: readonly string[];
  colourways: readonly ApparelColourway[];
};

const A = "/images/alpaca-sweater/variants";

export const apparel: readonly ApparelCollection[] = [
  {
    name: "El Patrón",
    slug: "alpaca-sweater",
    material: "100% baby alpaca · Peru",
    note: "Knitted in Peru from baby alpaca — softer than cashmere, warmer than wool, and naturally hypoallergenic.",
    /* One garment, three sizes, and the same three on every colourway. Held
       on the collection rather than repeated on all five. */
    sizes: ["Small", "Medium", "Large"],
    colourways: [
      {
        name: "Pastel",
        handle: "baby-alpaca-sweater-pastel",
        variantId: 45585335451842,
        cents: 10000,
        compareAtCents: 12500,
        available: true,
        image: `${A}/pastel-01.jpg`,
        swatch: "#d8cfc2",
      },
      {
        name: "Perdiz",
        handle: "baby-alpaca-sweater-perdiz",
        variantId: 45585334993090,
        cents: 10000,
        compareAtCents: 12500,
        available: true,
        image: `${A}/perdiz-01.jpg`,
        swatch: "#7d6a56",
      },
      {
        name: "Pink",
        handle: "alpaca-sweater-pink",
        variantId: 45585315496130,
        cents: 10000,
        compareAtCents: 12500,
        available: true,
        image: `${A}/pink-01.jpg`,
        swatch: "#c79aa2",
      },
      {
        name: "Tweed",
        handle: "alpaca-sweater-tweed",
        variantId: 45585268211906,
        cents: 10000,
        compareAtCents: 12500,
        available: true,
        image: `${A}/tweed-01.jpg`,
        swatch: "#6f6f6a",
      },
      {
        name: "X",
        handle: "alpaca-sweater-x",
        variantId: 45585333715138,
        cents: 10000,
        compareAtCents: 12500,
        available: true,
        image: `${A}/x-01.jpg`,
        swatch: "#2f2f31",
      },
    ],
  },
];
