/**
 * GENERATED by scripts/sync-catalogue.mjs — do not edit by hand.
 *
 * The live storefront's eyewear, one row per colourway: the Shopify handle
 * to link at, the price in cents, and whether it is in stock. Read from
 * https://arianoir.com/collections/all/products.json, which Shopify publishes without a
 * key.
 *
 * Re-run the script when the store changes. Editing this file instead
 * creates the second catalogue the script exists to prevent.
 *
 * Last synced: 2026-08-27
 */

export type CatalogueEntry = {
  colorway: string;
  /** Shopify product handle. Irregular — see the script's header. */
  handle: string;
  /** Numeric variant id, for /cart/<id>:<qty> checkout permalinks. */
  variantId: number;
  cents: number;
  available: boolean;
};

export const CATALOGUE: Record<string, readonly CatalogueEntry[]> = {
  "ahava": [
    { colorway: "Caramel Stripe", handle: "ahava-caramel-stripe", variantId: 45012907851970, cents: 20000, available: true },
    { colorway: "Dark Tortoise", handle: "ahava-dark-tortoise", variantId: 48568027381954, cents: 22500, available: true },
    { colorway: "Noir", handle: "ahava-noir", variantId: 45012905656514, cents: 20000, available: true },
    { colorway: "Root Beer Float", handle: "ahava", variantId: 45012895924418, cents: 20000, available: true },
    { colorway: "Rose", handle: "ahava-dreamy-rose", variantId: 45012910604482, cents: 20000, available: true },
    { colorway: "Tutti Frutti", handle: "ahava-tutti-frutti", variantId: 45012912701634, cents: 20000, available: true },
  ],
  "arca-i": [
    { colorway: "309 Blue", handle: "arca-309", variantId: 45010317672642, cents: 10000, available: true },
    { colorway: "K Black", handle: "arca-k", variantId: 45010318917826, cents: 10000, available: true },
    { colorway: "Proceso Brown", handle: "arca-proceso", variantId: 45010318459074, cents: 10000, available: true },
    { colorway: "Z White", handle: "arca-z", variantId: 45010321866946, cents: 10000, available: true },
  ],
  "arca-ii": [
    { colorway: "Caramel Stripe", handle: "arca-2-caramel-stripe", variantId: 48568187388098, cents: 20250, available: true },
    { colorway: "Dark Tortoise", handle: "arca-2-dark-tortoise", variantId: 45012892778690, cents: 12500, available: true },
    { colorway: "Dreamy Rose", handle: "arca-2-dreamy-rose", variantId: 45012891730114, cents: 12500, available: true },
    { colorway: "Noir", handle: "arca", variantId: 45012888191170, cents: 12500, available: true },
    { colorway: "Pixie Dust", handle: "arca-2-pixie-dust", variantId: 45012893106370, cents: 12500, available: true },
    { colorway: "Root Beer Float", handle: "arca-2-root-beer-float", variantId: 45012892418242, cents: 12500, available: true },
    { colorway: "Tutti Frutti", handle: "arca-2-tutti-frutti", variantId: 45012893073602, cents: 12500, available: true },
    { colorway: "Velvet Rose", handle: "arca-velvet-rose", variantId: 45012891369666, cents: 12500, available: true },
  ],
  "matriarca": [
    { colorway: "Black Wood", handle: "matriarca-black", variantId: 48642203189442, cents: 15000, available: false },
    { colorway: "Brown", handle: "matriarca", variantId: 45010325536962, cents: 17500, available: true },
    { colorway: "Midnight Noir", handle: "matriarca-black-polished", variantId: 45010328879298, cents: 17500, available: true },
  ],
  "monarca": [
    { colorway: "Caramel Stripe", handle: "monarca-caramel-stripe", variantId: 45012835369154, cents: 15000, available: true },
    { colorway: "Dark Tortoise", handle: "monarca-dark-tortoise", variantId: 45020183462082, cents: 15000, available: true },
    { colorway: "Dreamy Rose", handle: "monarca", variantId: 45012806140098, cents: 15000, available: true },
    { colorway: "Noir", handle: "monarca-noir", variantId: 45012820492482, cents: 15000, available: true },
    { colorway: "Pixie Dust", handle: "monarca-pixie-dust", variantId: 45012857585858, cents: 15000, available: true },
    { colorway: "Tutti Frutti", handle: "monarca-tutti-frutti", variantId: 45012847263938, cents: 15000, available: true },
    { colorway: "Velvet Rose", handle: "monarca-velvet-rose", variantId: 48568116314306, cents: 24750, available: true },
  ],
  "patriarca": [
    { colorway: "Black", handle: "patriarca-black", variantId: 45010330714306, cents: 17500, available: true },
    { colorway: "Brown", handle: "patriarca", variantId: 45010330124482, cents: 17500, available: true },
    { colorway: "Midnight Noir", handle: "patriarca-black-polished", variantId: 45010331205826, cents: 17500, available: true },
  ],
};
