/**
 * GENERATED by scripts/build-colourway-cards.mjs — do not edit by hand.
 *
 * The square card renders for the colourway wall: the whole 16:9 sill
 * fitted into a square so the temples are not cropped. One per colourway —
 * the wall zooms on hover rather than swapping the photograph. See the
 * script's header.
 *
 * Keyed by house slug, then by the SLUG of the colourway name.
 */

export type ColourwayCardArt = {
  image: string;
};

export const COLOURWAY_CARD_ART: Record<
  string,
  Record<string, ColourwayCardArt>
> = {
  "ahava": {
    "caramel-stripe": { image: "/images/ahava/variants/caramel-stripe-card.webp" },
    "dark-tortoise": { image: "/images/ahava/variants/dark-tortoise-card.webp" },
    "noir": { image: "/images/ahava/variants/noir-card.webp" },
    "root-beer-float": { image: "/images/ahava/variants/root-beer-float-card.webp" },
    "rose": { image: "/images/ahava/variants/rose-card.webp" },
    "tutti-frutti": { image: "/images/ahava/variants/tutti-frutti-card.webp" },
  },
  "arca-ii": {
    "caramel-stripe": { image: "/images/arca-ii/variants/caramel-stripe-card.webp" },
    "dark-tortoise": { image: "/images/arca-ii/variants/dark-tortoise-card.webp" },
    "dreamy-rose": { image: "/images/arca-ii/variants/dreamy-rose-card.webp" },
    "noir": { image: "/images/arca-ii/variants/noir-card.webp" },
    "pixie-dust": { image: "/images/arca-ii/variants/pixie-dust-card.webp" },
    "root-beer-float": { image: "/images/arca-ii/variants/root-beer-float-card.webp" },
    "tutti-frutti": { image: "/images/arca-ii/variants/tutti-frutti-card.webp" },
    "velvet-rose": { image: "/images/arca-ii/variants/velvet-rose-card.webp" },
  },
  "matriarca": {
    "brown": { image: "/images/matriarca/variants/brown-card.webp" },
    "midnight-noir": { image: "/images/matriarca/variants/midnight-noir-card.webp" },
  },
  "monarca": {
    "caramel-stripe": { image: "/images/monarca/variants/caramel-stripe-card.webp" },
    "dark-tortoise": { image: "/images/monarca/variants/dark-tortoise-card.webp" },
    "dreamy-rose": { image: "/images/monarca/variants/dreamy-rose-card.webp" },
    "noir": { image: "/images/monarca/variants/noir-card.webp" },
    "pixie-dust": { image: "/images/monarca/variants/pixie-dust-card.webp" },
    "tutti-frutti": { image: "/images/monarca/variants/tutti-frutti-card.webp" },
    "velvet-rose": { image: "/images/monarca/variants/velvet-rose-card.webp" },
  },
  "patriarca": {
    "black": { image: "/images/patriarca/variants/black-card.webp" },
    "brown": { image: "/images/patriarca/variants/brown-card.webp" },
    "midnight-noir": { image: "/images/patriarca/variants/midnight-noir-card.webp" },
  },
};

/** The slug the map is keyed by. Matches the filenames on disk. */
export function colourwayKey(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
}
