/**
 * Measure every plate under public/images and write their sizes to
 * src/lib/plate-sizes.ts.
 *
 * ---- Why this exists ----
 *
 * The buy page's column of photographs is a mixed set: the colourway shots
 * are 1920x1080 and ARCA I's macros are square. Held in one fixed box they
 * either crop (`cover`) or come out at different widths (`contain`), and
 * the second is what you see once the first is fixed — a square macro
 * rendering 44% narrower than the product shot above it, in a column whose
 * whole job is to be one column.
 *
 * The answer is for every plate to take the FULL width and set its own
 * height, which means knowing each plate's ratio before it loads. Read at
 * runtime that is a layout shift on every image; read here it is a number
 * in a file.
 *
 * ---- Why a generated file rather than a build step ----
 *
 * Same reason lib/catalogue.ts is generated and committed: the input is a
 * folder of files that changes when someone adds photography, not on every
 * build, and a committed manifest is greppable, diffable and reviewable.
 * Run this when plates are added or replaced:
 *
 *   node scripts/measure-plates.mjs
 *
 * Headers only. Nothing is decoded and no dependency is needed: a JPEG's
 * SOF marker and a PNG's IHDR both carry the dimensions in the first few
 * hundred bytes.
 */

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

/* fileURLToPath, not `.pathname`: this repository lives under a path with
   spaces in it, and a URL's pathname percent-encodes them. */
const ROOT = fileURLToPath(new URL("..", import.meta.url));
const IMAGES = join(ROOT, "public", "images");
const OUT = join(ROOT, "src", "lib", "plate-sizes.ts");

/** JPEG: walk the marker chain to the frame header. */
function jpeg(buf) {
  if (buf[0] !== 0xff || buf[1] !== 0xd8) return null;
  let i = 2;
  while (i + 9 < buf.length) {
    if (buf[i] !== 0xff) return null;
    const marker = buf[i + 1];
    /* Standalone markers carry no length. */
    if (marker === 0xd8 || marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      i += 2;
      continue;
    }
    const len = buf.readUInt16BE(i + 2);
    /* Any SOFn but the four that are not frame headers. */
    const isFrame =
      marker >= 0xc0 &&
      marker <= 0xcf &&
      marker !== 0xc4 &&
      marker !== 0xc8 &&
      marker !== 0xcc;
    if (isFrame) return [buf.readUInt16BE(i + 7), buf.readUInt16BE(i + 5)];
    i += 2 + len;
  }
  return null;
}

/** PNG: IHDR is always the first chunk, at a fixed offset. */
function png(buf) {
  if (buf.readUInt32BE(0) !== 0x89504e47) return null;
  return [buf.readUInt32BE(16), buf.readUInt32BE(20)];
}

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) walk(full, out);
    else out.push(full);
  }
  return out;
}

const sizes = [];
let skipped = 0;

for (const file of walk(IMAGES).sort()) {
  const lower = file.toLowerCase();
  const isJpg = lower.endsWith(".jpg") || lower.endsWith(".jpeg");
  const isPng = lower.endsWith(".png");
  if (!isJpg && !isPng) continue;

  /* 64KB is past the frame header of every file in this folder and a long
     way short of reading 281 photographs into memory. */
  const head = readFileSync(file).subarray(0, 65536);
  const dims = isPng ? png(head) : jpeg(head);
  if (!dims || !dims[0] || !dims[1]) {
    skipped += 1;
    console.warn("could not measure:", relative(ROOT, file));
    continue;
  }
  const url = "/" + relative(join(ROOT, "public"), file).split(sep).join("/");
  sizes.push([url, dims[0], dims[1]]);
}

const body = sizes.map(([url, w, h]) => `  "${url}": [${w}, ${h}],`).join("\n");

writeFileSync(
  OUT,
  `/**
 * GENERATED by scripts/measure-plates.mjs. Do not edit by hand.
 *
 * Every plate under public/images, as [width, height]. Read by
 * \`plateRatio\` in lib/shop, which is what lets a column of mixed-ratio
 * photographs render at ONE width with each plate setting its own height,
 * rather than at one height with each plate setting its own width.
 *
 * Re-run the script when photography is added or replaced.
 */

export const PLATE_SIZES: Record<string, readonly [number, number]> = {
${body}
};
`,
  "utf8",
);

console.log(`measured ${sizes.length} plates${skipped ? `, skipped ${skipped}` : ""}`);
console.log("wrote", relative(ROOT, OUT));
